### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by frankhale** [Autodesk/clearx#4]
Are there any plans to add Typescript definitions for this library?

**Comment by svapreddy** [comment]
No plans yet but I see value in having TypeScript definitions. Do you have any use cases in mind?

**Comment by frankhale** [comment]
I have not produced any yet but it is something I'm looking into.

**Comment by svapreddy** [comment]
@frankhale Working on typescript definitions.

**Comment by svapreddy** [comment]
@frankhale It's taking little longer than expected but we are close. I am doing some other improvements as part of this task to make Clearx work well with Functional Components. Thank you for waiting.

**Comment by frankhale** [comment]
No worries!! Thank you so much for this!!!!

**Comment by svapreddy** [comment]
@frankhale Please check the latest version of ClearX. It has gone through major refactor, and also it has type definitions now. Please check and let us know if it does not work for you.

**Comment by frankhale** [comment]
Thank you so much! I will give it a try!!!!
