### ISSUE TITLE
Async updates

### ISSUE THREAD

**Issue by matt-ewan-laws** [Autodesk/clearx#5]
I was wondering how one would go about with asyncronous store updates using clearx

**Comment by svapreddy** [comment]
@matt-ewan-laws Thanks for checking our Clearx. Do you have any example code that I can help you with?

**Comment by matt-ewan-laws** [comment]
A particular example would be making a GET request using fetch.

**Comment by svapreddy** [comment]
@matt-ewan-laws Have you tried setting the data in your async callback. For example, `store.set` or any other method to update the data.
